spring:
  profiles.active: dev

security:
  oauth2:
    resource:
      filter-order: 3
      jwt:
        key-value:
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAs1HLWx//4CM7PYYDdsE7
          0Ji42U/JIjkI8jlRp+Urx4P0/I2bPVZePw9WNDjcen560fmBlqt4NNzsEhOqi1tv
          25LvknTvNrUTl4L+u/jRY0kJpGcSBP/VtqdY0Yt6u+L/05VzMSLXr9PbhDw8nyhq
          7M/Y0wv7VQiFmeV4zK5lsYN787ii3ctouAg/VWFT2V5ZP24MLBGjb3s7Ipi8Wngp
          NIz/2umG/VYfnpZIy5cpqJLyLJKFJ02fTYsGcl6I23aQPpcsHhabEsjKUpF/ck4H
          XrBmadVQz9vFWxQVkUwpbMt827Zzkf2VnqIyVzmXsuY9gfiQeWLtmRvpw8KAZcOR
          jwIDAQAB
          -----END PUBLIC KEY-----

---

spring:
  profiles: dev
  h2:
    console:
      enabled: true
  datasource:
#    url: jdbc:mysql://localhost/dbname?autoReconnect=true&useUnicode=true&characterEncoding=utf8
#    username: user
#    password: pwd
    url: jdbc:h2:mem:dbname;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    data: classpath:import.sql

  # JPA로 사용할 데이터베이스 명시
  jpa:
#    database: mysql
    database: h2
    show-sql: true
    hibernate:
      ddl-auto: update
#      ddl-auto: create-drop

logging:
  config: classpath:logback-spring-debug.xml

---

spring:
  profiles: service
  datasource:
    url: jdbc:mysql://localhost/dbname?autoReconnect=true&useUnicode=true&characterEncoding=utf8
    username: user
    password: pwd

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update

server:
  port: 80
